server:
  port: 8000
spring:
  application:
    name: cloud-resource
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cloud?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
eureka:
  client:
    register-with-eureka: true #表示是否将自己注册进eurekaserver 默认true
    fetch-registry: true #是否从eurekaserver抓取自己有的注册信息，默认true，单节点无所谓，集群必须为true才能配合ribbon使用负载均衡
    service-url:
       #单机版 defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: cloudresource
    prefer-ip-address: true #访问路径可以显示ip地址
    lease-renewal-interval-in-seconds: 30 #eureka 客户端向服务器端发送心跳时间间隔，单位为秒（默认30秒）
    lease-expiration-duration-in-seconds: 90 #eureka 服务端在收到最好一次心跳后等待时间上限，单位为秒（默认90秒），超时将删除服务
  