

server:
  port: 8082
  servlet:
    context-path: /client1

security:
  oauth2:
    client:
      clientId: base-app03
      clientSecret: 123456
      user-authorization-uri: http://127.0.0.1:8081/oauth/authorize
      access-token-uri: http://127.0.0.1:8081/oauth/token
    resource:
      jwt:
        key-uri: http://127.0.0.1:8081/oauth/token_key
logging:
  level: 
    org:
      springframework:
        web: trace