server:
  port: 8061
  session:
    #session 超时时间，但在springboot中session时间最少是一分钟
    timeout: 60
spring:
  application:
    name: base-demo-service
  thymeleaf:
    cache: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cloud?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456
  session:
    store-type: redis
    redis:
      flush-mode: on-save
      namespace: spring:session
  redis:
    port: 6379
    database: 0
    host: 127.0.0.1
    password: 123456
    pool:
      max-active: 10
      max-idle: 10
      max-wait: -1
      min-idle: 0
      
mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.base.pojo


base:
  security:
    browser:
      loginType: JSON
      rememberMeSeconds: 3000
      #--没有配置时会自动返回json格式
      logoutUrl: /logout.html
      session: 
        maximumSessions: 1
        maxSessionsPreventsLogin: false
        sessionInvalidUrl: /demo-session-expire.html
    code:
      image:
        length: 2
      sms:
        length: 2
        dealUrl: /authen/mobile
    social:
      filterProcessesUrl: /qqLogin
      qq:
        providerId: callback.do
        app-id: 100550231
        app-secret: 69b6ab57b22f3c2fe6a6149274e3295e
      weixin:
        app-id: wxd99431bbff8305a0
        app-secret: 60f78681d063590a469f1b297feff3c4
    oauth2:
      clients:
        - clientId: base-app
          clientSecret: base-app-secret
          accessTokenValiditySeconds: 3600
          authorizedGrantTypes: 
            - password
            - refresh_token
          scopes: 
            - all
        - clientId: base-app2
          clientSecret: base-app-secret
          accessTokenValiditySeconds: 3600
          authorizedGrantTypes: 
            - password
            - refresh_token
          scopes: 
            - all
# mybatis-plus相关配置
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.base.pojo
  # 以下配置均有默认值,可以不设置
  global-config:
    db-config:
      #主键类型 AUTO:"数据库ID自增" INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
      #字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
      field-strategy: NOT_EMPTY
      #数据库类型
      db-type: MYSQL
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com:
      base:
        security:
          demo:
            mapper: debug
   
        
        
    
    
    